### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by zuikeaideren** [akhilpm/DroneDetectron2#26]
Hello,using the VOC2COCO file you gave, it can only convert xml files into json files, and the data set only has txt and image after downloading. Do I need to convert txt into xml and then into json files? If not, I would like to ask how to solve it?
also how should I change the code if I want to use my own data set?

**Comment by akhilpm** [comment]
This codebase extends the detectron2 that supports popular datasets like COCO, Pascal VOC, etc. So that means, I have to write custom register functions for VisDrone and DOTA datasets. Now if you want to change to another dataset, you can refer to how I did for the above-mentioned and change it on your own. You can refer to the detectron2 documentation also for this. 

Carefully check the code, it doesn't matter if the input data is in an XML or Txt file, just read it and convert it to JSON.
