### ISSUE TITLE
train FCOS_crop

### ISSUE THREAD

**Issue by aowuaaa** [akhilpm/DroneDetectron2#29]
I run the original code, and it throws an error. 
AssertionError: A prediction has class=10, but the dataset only has 10 classes and predicted class id should be in [0, 9].

When comparing R-CNN and SSOD, I found inconsistencies in 'crop_fcos.py'. I successfully ran it by uncommenting.
https://github.com/akhilpm/DroneDetectron2/blob/289fc0cb792a8c44d972ff6e5b0f7f058db16ab6/croptrain/modeling/meta_arch/crop_fcos.py#L156C70-L156C70

**Comment by akhilpm** [comment]
It is because I am not using the "others" class available in the Visdrone dataset (both for training and testing). The json annotation file I shared here ignores that category, so if you use that for training, it should work. 

Also, check the closed issues, this is already solved in few of them (for example #25)
